name: dev-blog
description: "[karriere.at](https://www.karriere.at) developer blog. Blogging about hacking and science."
meta_description: karriere.at developer blog. Blogging about hacking and science.

permalink:          /a/:title
timezone:           Europe/Vienna

markdown: kramdown
kramdown:
    input: GFM
logo: false
paginate: 30
baseurl: ''
domain_name: 'https://dev.karriere.at'
google_analytics: 'UA-237751-17'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Details for the RSS feed generator
url: 'https://dev.karriere.at'
author: 'karriere.at'

authors:
  fichtl:
    name: Fichtl
    bio-de: "Der bekennende Ursprungsinnviertler Fichtl ist einer der Brains von karriere.at. Wenn er nicht gerade an der Software herumschraubt, sind BÃ¼cher und Filme seine Leidenschaft. Legobauen seine Obsession."
    bio-en: "TODO"
  alex:
    name: Alex
    bio-de: "Dev-Ops Alex studierte an der FH Hagenberg. Bei karriere.at absolvierte er sein Berufspraktikum und beschÃ¤ftigt sich nun damit wie unsere Entwickler und Server arbeiten. In der Freizeit wird mit Freundin um die Welt gereist. Sogar dann sind BÃ¼cher, Kaffee und sein MacBook Air stÃ¤ndige Begleiter."
    bio-en: "TODO"
  mori:
    name: Mori
    bio-de: "Christian folgt stets seinem BauchgefÃ¼hl, und das hat ihn in das Entwicklungsteam von karriere.at gefÃ¼hrt. Neben seinem eBusiness Studium versucht er zusÃ¤tzlich seinen Tag mit Sport zu fÃ¼llen. Sein Motto: Think big, win the world."
    bio-en: "TODO"
  fred:
    name: Fred
    bio-de: "Fred macht sein Hobby gerade zum Beruf. Nicht nur bei karriere.at sondern auch in seiner Freizeit bastelt unser Lehrling an Software. Tut er das nicht, produziert der SÃ¼d-NiederÃ¶sterreicher oft Youtube-Videos oder widmet sich dem Elektro-Swing von Parov Stelar."
    bio-en: "TODO"
  markus:
    name: Markus
    bio-de: "Markus ist Web-Developer Marke Eigenbau. Soll heiÃŸen: Er hat sich seine Entwickler-Skills alle selbst beigebracht. Privat wird gekocht, mit BÃ¶gen geschossen und gegeocached."
    bio-en: "TODO"
  lenzi:
    name: Lenzi
    bio-de: "Lenzi ist ein ganz seltsamer Programmierer: Er trinkt keinen Kaffee, musiziert auf ganz analogen Instrumenten, in der Pause greift er schon mal zum Apfel statt zur Zigarette und er geht sogar gern hinaus ans Tageslicht (um beispielsweise Beachvolleyball zu spielen)."
    bio-en: "TODO"
  guenther:
    name: GÃ¼nther
    bio-de: "GÃ¼nther hat schon am Amiga 500 seine ersten BASIC-Programme entwickelt. Ein paar Jahr(zehnt)e spÃ¤ter macht er das auch beruflich - in Java. Bei karriere.at kann er seinen Hang zum Optimieren und Perfektionieren voll ausleben. Die nÃ¶tige Kraft (zum Tippen und Maus bewegen) und Ausdauer (fÃ¼r das lange Sitzen) sammelt er im Fitnesstudio und auf ausgedehnten Mountainbike-AusflÃ¼gen"
    bio-en: "TODO"
  gustl:
    name: Gustl
    twitter: pixelution
    bio-de: "Gustl ist Linzer mit Tiroler Wurzeln. Gustl ist Papa, FirmengrÃ¼nder und Webworker. Bei karriere.at ist der Multimedia-Freak Teil des Developer-Teams und bringt etwas Tiroler Flair in das grÃ¼ne Office an der Donau."
    bio-en: "TODO"
  paul:
    name: Paul
    bio-de: "Bewegungshungrig, abenteuerlustig, spontan: Drei Eigenschaften, die Developer Paul perfekt umreiÃŸen. Er hat wirklich immer etwas vor im FuÃŸballverein (ATSV Stein), bei der Freiwilligen Feuerwehr, im Sportverein seiner Heimatgemeinde. Zum Relaxen werden Serien geschaut und Technik-News gelesen."
    bio-en: "TODO"
  wolfgang:
    name: Wolfgang
    bio-de: "Wolfgang ist Product Owner fÃ¼r Core Services und interne Software bei karriere.at. Noch Fragen? Also: Er sorgt dafÃ¼r, dass die KarrierekÃ¶pfe mit karriere.at bestmÃ¶glich arbeiten kÃ¶nnen und alle Systeme wie am SchnÃ¼rchen laufen. Privat: Familie, Tochter, Katzen, Gitarre, BÃ¼cher und Metal!"
    bio-en: "TODO"
  juergen:
    name: JÃ¼rgen
    bio-de: "JÃ¼rgen ist Master. Was er als Praktikant bei karriere.at begann, zeigt er heute im Dev-Team in hÃ¶chster Perfektion. Musik ist seine Passion, Zocken ebenso. Sein freundliches Wesen erfreut nicht nur Mitmenschen und Kollegen, er ist auch ein groÃŸer Tierfreund, der zwei Chinchillas und zwei Katzen sein Eigen nennt."
    bio-en: "TODO"
  manu:
    name: Manuel
    bio-de: "Manuel ist Lead Web Developer bei karriere.at, Lehrbeauftragter an der FH Hagenberg und schreibt auch privat regelmÃ¤ÃŸig auf [manu.ninja](https://manu.ninja/) Ã¼ber Front-End Development, Games und Digital Art.<br>[@manuelwieser](https://twitter.com/manuelwieser)"
    bio-en: "Manuel is Lead Web Developer at karriere.at, lecturer at the University of Applied Sciences Upper Austria and writes about Front-End Development, Games und Digital Art on his personal blog [manu.ninja](https://manu.ninja/).<br>[@manuelwieser](https://twitter.com/manuelwieser)"
    twitter: manuelwieser
  anita:
    name: Anita
    bio-de: "Leidenschaft spielt in Anitas Leben eine groÃŸe Rolle. Ihr Motto: Alles, was man mit Liebe macht, wird auch gut: Ob Design, Kochen oder GemÃ¼se-ZÃ¼chten. Lesen - natÃ¼rlich in Papierform! - gehÃ¶rt zur Entspannung dazu."
    bio-en: "TODO"
  michael:
    name: Michael
    bio-de: "Wenn Michael gefragt wird, was er beruflich macht, sagt er \"Scrum Master\". Wenn er dann in ein fragendes Gesicht blickt, sagt er \"Agile Coach\". Wenn dann die Stirnrunzeln bei seinem GegenÃ¼ber noch grÃ¶ÃŸer werden, wechselt er das Thema und redet Ã¼ber das Motorradfahren, Tai Chi oder SÃ¼ÃŸigkeiten."
    bio-en: "TODO"
  sharon:
    name: Sharon
    bio-de: "Ausdauer zÃ¤hlt zu Sharons grÃ¶ÃŸten StÃ¤rken. Und die braucht sie auch. Denn bevor bei karriere.at neue Codes zur Anwendung kommen, werden sie von der Gitarre und Tenor-BlockflÃ¶te spielenden Entspannungs-HÃ¤klerin auf Herz und Nieren geprÃ¼ft. Steht Sport auf dem Programm, ist ebenfalls Ausdauer gefragt beim Klettern, Radfahren und Schwimmen."
    bio-en: "TODO"
  klemens:
    name: "Klemens ğŸš¬"
    bio-de: "Frontend Devloper bei karriere.at. Loves javascript, beer and coffee. I'm on [Twitter](http://twitter.com/thisisgordon) and [GitHub](https://github.com/k9ordon)"
    bio-en: "TODO"
    twitter: thisisgordon
  jakob:
    name: Jakob
    twitter: jay_linski
    bio-de: "Wer Jakob beschreiben will, muss auf Klischees verzichten. Er liebt die Bewegung (Snowboarden, Wandern, Slacklinen), steht auf Neurofunk, trinkt keinen Kaffee und fÃ¤hrt Supermoto. Der MÃ¼hlviertler ist aber Hacker mit Leib und Seele: bei karriere.at als Web Developer, privat als White Hat Hacker."
    bio-en: "TODO"
  markusv:
    name: Markus V.
    bio-de: "Markus ist Software Developer bei [jobs.at](https://www.jobs.at), einem Spin-off von karriere.at. Was ist bei ihm privat so los? ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ğŸ•ğŸƒâ€ğŸ‹ï¸ğŸ¥¦â˜•ğŸ·. Erreichen kann man ihn auf [Twitter](https://twitter.com/mvieghofer)."
    bio-en: "TODO"
    twitter: mvieghofer
  hannes:
    name: Hannes
    bio-de: "Johannes sorgt dafÃ¼r, dass das Backend von karriere.at perfekt lÃ¤uft, nÃ¤mlich als PHP Web Developer. Dass man bei dieser Aufgabe Ausgleich braucht, liegt auf der Hand: Der leidenschaftliche Papa verbringt seine Zeit am liebsten mit Tochter und Ehefrau aber auch beim Laufen und im Sportverein."
    bio-en: "TODO"
    twitter: fetzi_io
  christinaf:
    name: Christina Feilmayr
    bio-de: "Data Scientist Christina beschreibt sich selbst als leidenschaftliche Analystin, die in Konzepten denkt und gern Neues ausprobiert. Je innovativer, desto besser. In ihrem Leben drauÃŸen beschÃ¤ftigt sich die â€Bubenmamaâ€œ mit â€Bubendingsâ€œ: Autos, WerkzeugbÃ¤nken und Duplo-Lego. Sonst: Sport, Laufen, Foodblogs und Kochen!"
    bio-en: "TODO"
  dominik:
    name: Dominik
    bio-de: "Dominik beschreibt sich selbst als ruhig, hilfsbereit und relaxed - also stressresistent bis in die letzte Faser. Als Ausgleich zu seinem Job Web Developer entspannt er bei Strategie-Games, trifft sich mit Freunden oder chillt auf Festivals oder beim Fortgehen."
    bio-en: "TODO"
  plengauer:
    name: Philipp Lengauer
    twitter: F1PSii
    bio-de: "Offen, ehrlich, genau, freundlich und engagiert: Philipp â€“ seines Zeichens Webentwickler bei karriere.at. Auch in der Freizeit gibt er sich keine Zeit fÃ¼r Stillstand. Sport, Motorradfahren und Freunde sind ihm da das Wichtigste."
    bio-en: "TODO"
  stefank:
    name: Stefan K.
    bio-de: "Stefan ist Softwareentwickler bei karriere.at â€“ und jetzt nach dem Studium nebenbei noch HÃ¤usl-Renovierer. Dass ihm neben Arbeit, Haus und Garten auch noch genÃ¼gend Zeit fÃ¼r Freundin, Haustiere, Musik und PS4-Zocken bleibt, spricht fÃ¼r sein Selbstmanagement â€“ Chapeau!"
    bio-en: "TODO"
